// Generated by scripts/generate_canonical_bindings.py; do not edit by hand.
// Source: https://w3id.org/riopa/schema/canonical-crosswalk/v1

export type CanonicalCrosswalkConfidence =
  "unknown" |
  "low" |
  "medium" |
  "high" |
  "disputed" |
  "inapplicable";

export interface CanonicalCrosswalkSourceAssertion {
  readonly source_id: string;
  readonly label: string;
}

export interface CanonicalCrosswalkValidTime {
  readonly from: string;
  readonly to: string | null;
}

export interface CanonicalCrosswalkClaim {
  readonly mapping_id: string;
  readonly source_assertion: CanonicalCrosswalkSourceAssertion;
  readonly canonical_id: string;
  readonly method: string;
  readonly confidence: CanonicalCrosswalkConfidence;
  readonly reviewer: string;
  readonly valid_time: CanonicalCrosswalkValidTime;
  readonly evidence: ReadonlyArray<string>;
}
