#!/usr/bin/env python3
"""Generate the bounded TypeScript binding for the canonical crosswalk schema."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

OBJECT_NAMES = {
    "source_assertion": "CanonicalCrosswalkSourceAssertion",
    "valid_time": "CanonicalCrosswalkValidTime",
}


def _typescript_type(name: str, schema: dict[str, Any]) -> str:
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    value_type = schema.get("type")
    if isinstance(value_type, list):
        return " | ".join("null" if item == "null" else item for item in value_type)
    if value_type == "array":
        return f"ReadonlyArray<{_typescript_type(name, schema['items'])}>"
    if value_type == "object":
        try:
            return OBJECT_NAMES[name]
        except KeyError as exc:
            raise ValueError(f"no TypeScript interface name registered for {name}") from exc
    return {"integer": "number", "number": "number"}.get(str(value_type), str(value_type))


def _interface(name: str, schema: dict[str, Any]) -> list[str]:
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for property_name, property_schema in schema.get("properties", {}).items():
        optional = "" if property_name in required else "?"
        lines.append(
            f"  readonly {property_name}{optional}: "
            f"{_typescript_type(property_name, property_schema)};"
        )
    return [*lines, "}"]


def render_binding(schema: dict[str, Any]) -> str:
    """Render a deterministic declaration file and fail on unsupported schema drift."""

    properties = schema.get("properties")
    if not isinstance(properties, dict):
        raise ValueError("canonical crosswalk schema properties must be an object")
    for property_name in OBJECT_NAMES:
        nested = properties.get(property_name)
        if not isinstance(nested, dict) or nested.get("type") != "object":
            raise ValueError(f"{property_name} must remain an inline object schema")
    confidence = properties.get("confidence")
    if not isinstance(confidence, dict) or not isinstance(confidence.get("enum"), list):
        raise ValueError("confidence must remain an enum")

    output = [
        "// Generated by scripts/generate_canonical_bindings.py; do not edit by hand.",
        f"// Source: {schema.get('$id', 'schemas/canonical-crosswalk.schema.json')}",
        "",
        "export type CanonicalCrosswalkConfidence =",
    ]
    enum_values = confidence["enum"]
    for index, value in enumerate(enum_values):
        suffix = ";" if index == len(enum_values) - 1 else " |"
        output.append(f"  {json.dumps(value)}{suffix}")
    output.extend([""])
    output.extend(_interface(OBJECT_NAMES["source_assertion"], properties["source_assertion"]))
    output.extend([""])
    output.extend(_interface(OBJECT_NAMES["valid_time"], properties["valid_time"]))
    output.extend([""])

    claim_schema = dict(schema)
    claim_properties = dict(properties)
    claim_properties["confidence"] = {"type": "CanonicalCrosswalkConfidence"}
    claim_schema["properties"] = claim_properties
    output.extend(_interface("CanonicalCrosswalkClaim", claim_schema))
    return "\n".join(output) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--schema", type=Path, default=Path("schemas/canonical-crosswalk.schema.json")
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("bindings/typescript/canonical-crosswalk-v1.d.ts"),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    schema = json.loads(args.schema.read_text(encoding="utf-8"))
    rendered = render_binding(schema)
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"generated binding is stale: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
